# Generated by Django 5.1.3 on 2024-11-22 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agriagency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phoneno', models.BigIntegerField()),
                ('password', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=700, null=True)),
            ],
            options={
                'db_table': 'agriagency',
            },
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phoneno', models.BigIntegerField()),
                ('password', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernumber', models.CharField(max_length=200)),
                ('orderdate', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('phoneno', models.BigIntegerField()),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('orderstatus', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentstatus', models.CharField(default='pending', max_length=200)),
                ('transactionid', models.CharField(max_length=200)),
                ('paymentmode', models.CharField(default='paypal', max_length=100)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agriapp.customer')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agriapp.order')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('product_price', models.FloatField(null=True)),
                ('product_description', models.CharField(max_length=500, null=True)),
                ('status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('UNAPPROVED', 'UNAPPROVED')], default='pending', max_length=100)),
                ('agriagency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agriapp.agriagency')),
            ],
            options={
                'db_table': 'Agri',
            },
        ),
        migrations.CreateModel(
            name='orderdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernumber', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('totalprice', models.IntegerField()),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agriapp.customer')),
                ('paymentid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Agriapp.payment')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agriapp.product')),
            ],
            options={
                'db_table': 'orderdetail',
            },
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('totalamount', models.FloatField()),
                ('custid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agriapp.customer')),
                ('pac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agriapp.product')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
