# Generated by Django 5.1.3 on 2024-11-23 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agriapp', '0002_alter_agriagency_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='agriagency_id',
            new_name='agriagencyid',
        ),
    ]
